# Generated by Django 5.0.7 on 2025-03-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wallet',
        ),
    ]
