# Generated by Django 5.0.7 on 2025-04-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0002_remove_profile_country_remove_profile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('hotel', 'Hotel')], default='customer', max_length=10),
        ),
    ]
