# Generated by Django 5.0.7 on 2025-03-06 13:06

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_saved_booking_saved_amount_remove_hotel_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2000)),
                ('discount', models.IntegerField(default=1)),
                ('type', models.CharField(default='Percentage', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_upto', models.DateTimeField()),
                ('coupon_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', length=8, max_length=15, prefix='', unique=True)),
            ],
        ),
    ]
