# Generated by Django 5.0.7 on 2025-03-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupn',
            field=models.ManyToManyField(blank=True, to='hotel.coupon'),
        ),
    ]
