# Generated by Django 5.0.7 on 2025-03-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_booking_coupn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='coupn',
            new_name='coupon',
        ),
    ]
