# Generated by Django 5.0.7 on 2025-03-08 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rename_coupn_booking_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
