# Generated by Django 5.0.7 on 2025-03-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_coupon_booking_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturant',
            old_name='resturant_number',
            new_name='table_number',
        ),
    ]
