# Generated by Django 5.0.7 on 2025-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_rename_resturant_number_resturant_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='hotel_gallery'),
        ),
    ]
