# Generated by Django 5.0.7 on 2025-03-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_resturant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturant',
            name='image',
        ),
        migrations.AddField(
            model_name='resturant',
            name='number_of_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resturant',
            name='table_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
