# Generated by Django 5.0.7 on 2025-04-07 04:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_resturant_image_resturant_number_of_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
