# Generated by Django 5.0.7 on 2025-04-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_hotel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='user',
            new_name='owner',
        ),
    ]
