# Generated by Django 5.0.7 on 2025-04-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_rename_user_hotel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotel_gallery'),
        ),
    ]
