# Generated by Django 5.0.7 on 2025-04-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to='hotel_gallery/'),
        ),
    ]
