# Generated by Django 5.0.7 on 2025-04-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aa'),
        ),
    ]
