# Generated by Django 5.0.7 on 2025-04-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_resturant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel'),
        ),
    ]
