# Generated by Django 5.0.7 on 2025-04-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_coupon_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturant',
            name='image',
        ),
    ]
