# Generated by Django 5.0.7 on 2025-04-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_remove_resturant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='resturant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.resturant'),
        ),
    ]
