# Generated by Django 5.0.7 on 2025-04-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_booking_check_in_time_booking_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
