# Generated by Django 5.0.7 on 2025-04-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_booking_checked_in_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checked_in_date',
        ),
    ]
