# Generated by Django 5.0.7 on 2025-04-12 13:15

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_remove_booking_checked_in_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='resturant',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_time',
        ),
        migrations.CreateModel(
            name='ResturantBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('rbooking_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', length=8, max_length=15, prefix='', unique=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel')),
                ('number_of_seats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resturant_bookings_by_number_of_seats', to='hotel.resturant')),
                ('resturant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resturant_bookings', to='hotel.resturant')),
                ('table_capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resturant_bookings_by_table_capacity', to='hotel.resturant')),
                ('table_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resturant_bookings_by_table_number', to='hotel.resturant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
