# Generated by Django 5.0.7 on 2025-04-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_remove_booking_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantbooking',
            name='total_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
