# Generated by Django 5.0.7 on 2025-04-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_resturantbooking_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturantbooking',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='resturantbooking',
            name='resturant',
        ),
        migrations.RemoveField(
            model_name='resturantbooking',
            name='table_capacity',
        ),
        migrations.RemoveField(
            model_name='resturantbooking',
            name='table_number',
        ),
        migrations.AddField(
            model_name='resturantbooking',
            name='tables',
            field=models.ManyToManyField(related_name='restaurant_table_bookings', to='hotel.resturant'),
        ),
    ]
