# Generated by Django 5.0.7 on 2025-04-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_remove_resturantbooking_number_of_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantbooking',
            name='table_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
