# Generated by Django 5.0.7 on 2025-04-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelfeatures',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='HotelFaqs',
        ),
        migrations.DeleteModel(
            name='HotelFeatures',
        ),
    ]
